### PR TITLE
small typo

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**

### CODE REVIEW

**Comment by davestewart** [comment]
Ha! Good catch

**Comment by CharlesOkwuagwu** [comment]
Hi David.

I've been looking for  some simple direction of where and how to use `axios-actions` in relation to  `vuex-pathify`.

I know they solve two different things ,but it would be good to have your first hand take on best practice using both - together (save us the guess-work)

**Comment by davestewart** [comment]
Hey Charles,

Going "all in" eh!?

Well, I've been moving away from using Vuex for *everything* these days, especially to do with CRUD. Rather, I only use Vuex if I really need the state to be shared.

Axios Actions helps here, as you can set up the service independent of Vuex, and just call the API directly; no need to go via Vuex.

That being the case, set up a service anywhere you like, and import anywhere you like.

If you do want to use it in a Vuex action, you can just replace your previous Axios setup:

```js
import widgets from '../services/api/widgets'

const actions = {
  upload({commit}, payload) {
    widgets.upload(payload).then(data => commit('widgets', data))
  }
}
```

Does that help?

I'm going to break out the docs for version 3 in to separate pages, hopefully that will make things a bit easier to follow.

**Comment by CharlesOkwuagwu** [comment]
hmm. I guess the new docs will help clarify more...

But please use very - simple examples in the docs to ensure we can grasp at once without resorting to running the demo.

**Comment by davestewart** [comment]
OK. 

The new Getting Started section was going to look like this:

### Usage

Set up your URLs in one place:


```js
// config/urls/widgets.js
const urls = {
  // basic GET usage
  search: 'api/products/widgets?category=:category',
  
  // inline method config
  update: 'POST api/products/widgets/:id',
  
  // custom config
  delete: {
    url: 'api/products/widgets/:id',
    method: 'post',
    headers: {
      'Authorization': token,
      'Content-Type': 'application/json'
    }
  },
}
```

Then, instantiate a service:

```js
// services/api/widgets.js
export default new ApiGroup(axios, urls)
```

And use where needed:

```js
// anywhere
widgets.search(category).then( ... )
widgets.update(data).then( ... )
widgets.delete(id).then( ... )
```

What do you think?

**Comment by davestewart** [comment]
Perhaps I can make the code for the other classes more explicit as well.

**Comment by CharlesOkwuagwu** [comment]
This Looks Good And is easily understandable .. but see my actual usage:

```
import axios from 'axios'
import {
  ApiGroup
} from 'axios-actions'

const live = false
const token = localStorage.getItem('auth-token')

export const rootURL = live ? 'http://my-live-path/rmas-api/' : 'https://localhost:44304/'

export const api = new ApiGroup(
  axios.create({
    timeout: 180000,
    baseURL: live ? 'http://my-live-path/rmas-api/api/' : 'https://localhost:44304/api/',
    headers: token ? {
      Authorization: `Bearer ${token}`
    } : {}
  }), {
    login: 'POST login',
    run_report: 'POST run_report',

    batch_get: 'batch_get/:batchid',
    batch_save: 'POST batch_save',
    bizunits_list: 'bizunits_list',
    bizunits_save: 'POST bizunits_save',
    dashboard_refresh: 'dashboard_refresh',
    portfolio_list: 'portfolio_list',
    portfolio_save: 'POST portfolio_save',
    report_update_unitcode: 'POST report_update_unitcode',
    reports_list: 'reports_list',
    runlog_list: 'runlog_list/:batchid',
    runlog_save: 'POST runlog_save',
    runlog_user: 'runlog_user/:userid/:count',
    signoff_update: 'POST signoff_update',
    user_delete: 'POST user_delete/:userid',
    user_get: 'user_get/:userid',
    user_list: 'user_list/:unitcode',
    user_save: 'POST user_save/:userid',
    validator_save: 'POST validator_save'
  }
)

api.use('data')

```

We don't all adhere to traditional `REST` ...
I just using this for web-function call ... sees simple to me

**Comment by davestewart** [comment]
Yeah, looks good!

I would probably separate out the various top-level domains, and export various ApiGroups rather than one big one with `_` separating the tasks.

This way you can also save data on the service if you want to with callbacks.

**Pull request merged**
